### ISSUE TITLE
月野木ちろるTwitch対応

### ISSUE THREAD

**Issue by tashF75** [nejire957/774today#1]
いつも便利に使わせていただいております．ありがとうございます．

月野木ちろるさんのTwitchがここ数日で活発に動いています．ご対応いただけると嬉しいです．

私が調べた限りですが，おそらく月野木ちろる先生の channel IDは以下だと思います．
"channel":"tirol_tsukinoki","channel_id":1094762249
（Twitchのページをブラウザで開き，F12→ channel_idで検索して出てきたtokenを見ています）

もっと貢献できることがあれば嬉しいのですが，私自身でコードを読み解いて改修等するのは時間がかかりそうです．
まずはIssueでのご連絡とさせてください．

お忙しいところすみません．よろしくお願いいたします．

**Comment by nejire957** [comment]
ご連絡ありがとうございます。
Issueに気づかず、返信が遅くなり申し訳ありません。

この返信を書いている時点で、月野木ちろるさんのTwitchアカウントには対応しています。
（いつ対応したのかは忘れました）
もしご視聴の環境で月野木ちろるさんのTwitch配信が表示されないようであればご連絡ください。

ななしトゥデイの機能・品質は不十分であり、開発管理方法にも不適切な所が多くあります。
個人が無償で公開しているものですので、何卒ご容赦ください。

本件以外にもご意見・ご要望がありましたら、ぜひお知らせください。
よろしくお願いいたします。
